#   Napisati potprogram u asemblerskom jeziku koji implementira množenje sabiranjem i
#   pomeranjem:

#       a. C program za ovaj zadatak u dvostrukoj preciznosti, kao i potpis funkcije, dostupni su
#           u .c fajlu u direktorijumu z5_mnozenje
#       
#       b. Objašnjenje logike, kao i deo rešenja (deo sa glavnom logikom), dostupni su u
#           praktikumu u glavi 7.3





# pogledati z5_mnozenje u folderuu resenja