# Potprogram za postavljanje pariteta 16-bitnog broja
# Imenko Prezimić ra1234

#   int SetParity(unsigned short int* v)


#   3. Napisati potprogram u asemblerskom jeziku kojim se određuje paritet za 15-bitnu vrednost:
#       a. int SetParity(unsigned short int* vrednost)
#       b. Program vraća vrednost bita pariteta (1 ili 0)
#       c. Program prima 16-bitnu vrednost po adresi; njen najviši bit je rezervisan za bit
#           parnosti, i potprogram treba da ovaj bit postavi na odgovarajuću vrednost; ostalih 15
#           bitova predstavljaju bitove realnog podatka za koji se određuje paritet







# OVO JE OPET ISTO KAO ZADACI BEZ RESENJA SAMO   L A K S E
# pogledati onaj zadatak (valjda z2) gde se dobija NIZ BROJEVA I PROVERAVA DA LI JE NJIMA DOBRO SETTOVAN PARITET

# zasto sugavo nisam prvo radila ove zadatke